// import MainFile from './components/responsive ui/MainFile'
'use-client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const inter = Inter({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'ISCP - Integrated Supply Chain Planning',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container'>
        {children}
        <ToastContainer/>
      </body>
    </html>
  )
}
